version: '3.9'

services:
  db:
    container_name: "db_carWash"
    image: "postgres"
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=carWash
      - POSTGRES_USER=carWash
      - POSTGRES_PASSWORD=carWash
    volumes:
      - db_data:\postgres_data

volumes:
  db_data: